export const data = [
  {
    id: '1',
    brand: 'Soul hygge',
    name: 'HOT BREAD',
    category: 'Scented candle',
    discription: 'Close your eyes and imagine the melodious crackling of a fireplace in a country house',
    price: '47',
    stock: '20',
    thumbnailNumber: '1',
    images: [],
  },
  {
    id: '2',
    brand: 'Soul hygge',
    name: 'HOT BREAD',
    category: 'Scented candle',
    discription: 'Close your eyes and imagine the melodious crackling of a fireplace in a country house',
    price: '47',
    stock: '20',
    thumbnailNumber: '2',
    images: [],
  },
  {
    id: '3',
    brand: 'Soul hygge',
    name: 'HOT BREAD',
    category: 'Scented candle',
    discription: 'Close your eyes and imagine the melodious crackling of a fireplace in a country house',
    price: '47',
    stock: '20',
    thumbnailNumber: '5',
    images: [],
  },
  {
    id: '4',
    brand: 'Soul hygge',
    name: 'HOT BREAD',
    category: 'Scented candle',
    discription: 'Close your eyes and imagine the melodious crackling of a fireplace in a country house',
    price: '47',
    stock: '20',
    thumbnailNumber: '4',
    images: [],
  }
]
// "id":1,"title":"iPhone 9","description":"An apple mobile which is nothing like apple","price":549,"discountPercentage":12.96,"rating":4.69,"stock":94,"brand":"Apple","category":"smartphones","thumbnail":"https://i.dummyjson.com/data/products/1/thumbnail.jpg","images":["https://i.dummyjson.com/data/products/1/1.jpg","https://i.dummyjson.com/data/products/1/2.jpg","https://i.dummyjson.com/data/products/1/3.jpg","https://i.dummyjson.com/data/products/1/4.jpg","https://i.dummyjson.com/data/products/1/thumbnail.jpg"]},